### PR TITLE
tests: add schema to test cases

### LINKED ISSUE #213: Test errors and warnings
When running tests, several errors and warnings are raised. This clouds the output and makes it difficult to track down real issues with test cases.

Image

### PR DESCRIPTION
**Pull request by rekt-hard**
## Description

Tests

#### What does this PR do?

In a unit test, only the tested component is of interest. Child components will have their own tests thus there is no need to verify their attributes. Adding `CUSTOM_ELEMENTS_SCHEMA` or `NO_ERRORS_SCHEMA` to the testbed suppresses the warnings about child component attributes.

### Checks

- [ ] Summary updated
- [ ] Version view updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes #213

### CODE REVIEW

**Comment by lpandath** [comment]
@rekt-hard whilte I added an issue to test the test cases and saw that we also have this warning. Was this intended to leave it? 
`WARN: 'NG0313: Multiple pipes match the name translate in the 'DmpActionsComponent' component. check the imports of this module'      `

**Comment by rekt-hard** [comment]
@lpandath: These should be addressed as well. I did not yet have time to do so. We can leave this PR open and fix them here or create a separate PR.

**Comment by rekt-hard** [comment]
No more Angular related errors or warnings reported

**Review by lpandath — APPROVED** [review]

**Comment by lpandath** [comment]
> No more Angular related errors or warnings reported
Great, thank you!

**Pull request merged**
