### PR TITLE
214 global add new damap logo

### LINKED ISSUE #214: Global: Add new Damap Logo
**Changes**
Now that we have a logo and favicon, we should use it.
Replace the favicon with the damap favicon and the TU-Wien logo in the upper right with the damap logo. 
Both are accessible at https://colab.tuwien.ac.at/display/SRSI/DAMAP+logo
They also neeed to be colored in the Damap blue.

### PR DESCRIPTION
**Pull request by lpandath**
## Description

Replace the favicon and change the TU-Wien logo with the new logo and design. 

### Checks

- [ ] Summary updated
- [ ] Version view updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes GH-

### CODE REVIEW

**Comment by ValentinFutterer** [comment]
Can you color the favicon in the primary blue color that damap uses throughout its design - the yellow is not very fitting. Also i like the threecolored damap logo, but maybe it should also be colored in the standard damap-blue? @DerekMolnar what do you say? This is how it looks now.
image

**Comment by lpandath** [comment]
> Can you color the favicon in the primary blue color that damap uses throughout its design - the yellow is not very fitting. Also i like the threecolored damap logo, but maybe it should also be colored in the standard damap-blue? @DerekMolnar what do you say? This is how it looks now. image

@ValentinFutterer i showed yesterday Derek, but of course you can let me know if you guys want to have different changes.

**Comment by DerekMolnar** [comment]
@ValentinFutterer and I discussed and agreed that the 3 color logo looks best and should be used.  I couldn't see the image posted for the Favicon, but believe that dark blue will look best.  Let me know if further clarification is needed @lpandath .  Thanks for your help!

**Comment by lpandath** [comment]
@ValentinFutterer 
image

**Review by ValentinFutterer — APPROVED** [review]
Yeah looks good nice work 👍

**Pull request merged**
