### PR TITLE
dataset: add file format attribute

### LINKED ISSUE #40: Add a format value to dataset info
Datasets should have an additional free text input, where data format can be set (e.g. 'PDF').
Ideally the use of FITS component to automatically determine the data type should fill this field out automatically as well.

### PR DESCRIPTION
**Pull request by rekt-hard**
## Description

Feature
#### What does this PR do?

Add file attribute format to dataset.
Show attribute in new dataset table and new dataset dialog.

image
image

#### Dependencies

depends on https://github.com/tuwien-csd/damap-backend/pull/238
### Checks

- [ ] Summary updated
- [ ] Version view updated
- [ ] Documentation added
- [ ] Tests added
- [ ] E2e tests created
- [ ] Successfully ran e2e tests before merge

closes #40

### CODE REVIEW

**Review by ValentinFutterer — APPROVED** [review]
Works perfectly!

**Comment by rekt-hard** [comment]
Added info for file format
Screenshot from 2024-08-14 13-17-30
Screenshot from 2024-08-14 13-17-53

**Comment by ValentinFutterer** [comment]
I really like the tooltip, but it seems like it removed some spacing. 
image

**Comment by rekt-hard** [comment]
Good catch, thank you. Fixed it now (had the `matPrefix` attribute set)
image

**Pull request merged**
